version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: LinkGenerator
  go-service:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - postgres